# Generated by Django 4.2.7 on 2025-07-31 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='Issue size in crores', max_digits=15)),
                ('price_range_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_range_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('open_date', models.DateField(help_text='IPO opening date')),
                ('close_date', models.DateField(help_text='IPO closing date')),
                ('listing_date', models.DateField(help_text='Expected listing date')),
                ('board', models.CharField(choices=[('MAIN', 'Main Board'), ('SME', 'SME Board')], default='MAIN', max_length=10)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LISTED', 'Listed'), ('WITHDRAWN', 'Withdrawn')], default='UPCOMING', max_length=20)),
                ('lot_size', models.IntegerField(help_text='Minimum lot size')),
                ('total_subscription', models.DecimalField(decimal_places=2, default=0.0, help_text='Total subscription in times', max_digits=10)),
                ('retail_subscription', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail subscription in times', max_digits=10)),
                ('qib_subscription', models.DecimalField(decimal_places=2, default=0.0, help_text='QIB subscription in times', max_digits=10)),
                ('nii_subscription', models.DecimalField(decimal_places=2, default=0.0, help_text='NII subscription in times', max_digits=10)),
                ('rhp_document', models.FileField(blank=True, help_text='Red Herring Prospectus', null=True, upload_to='documents/rhps/')),
                ('drhp_document', models.FileField(blank=True, help_text='Draft Red Herring Prospectus', null=True, upload_to='documents/drhps/')),
                ('registrar', models.CharField(blank=True, help_text='Registrar to the issue', max_length=255, null=True)),
                ('lead_managers', models.TextField(blank=True, help_text='Lead managers (comma separated)', null=True)),
                ('listing_gains', models.DecimalField(blank=True, decimal_places=2, help_text='Listing gains in percentage', max_digits=10, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current market price', max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured IPO')),
                ('is_recommended', models.BooleanField(default=False, help_text='Mark as recommended IPO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ipos', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ipos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPONews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='ipos.ipo')),
            ],
            options={
                'verbose_name_plural': 'IPO News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RHP', 'Red Herring Prospectus'), ('DRHP', 'Draft Red Herring Prospectus'), ('PROSPECTUS', 'Prospectus'), ('APPLICATION', 'Application Form'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ipo_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ipos.ipo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
