# Generated by Django 4.2.7 on 2025-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='nii_subscription',
        ),
        migrations.RemoveField(
            model_name='ipo',
            name='qib_subscription',
        ),
        migrations.AddField(
            model_name='ipo',
            name='institutional_subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Institutional investor subscription in times', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='retail_subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Retail investor subscription in times', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='total_subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total subscription in times (e.g., 2.5 means 2.5x subscribed)', max_digits=5),
        ),
    ]
